### ISSUE TITLE
"Finner ikke boken."

### ISSUE THREAD

**Issue by henrikholen** [arve0/NBLeser#2]
Får ikke lest noen bøker, får bare opp "Finner ikke boken." på alle titler.

**Comment by arve0** [comment]
Hei, takk for tilbakemeldingen.
Kan du komme med et eksempel, eller gjelder det absolutt alle bøker?

**Comment by henrikholen** [comment]
Hei, takk for raskt svar.
Nå fungerer alt som normalt! Tusen takk for at du ordnet det.

**Comment by arve0** [comment]
Jeg har ikke ordnet noe, kanskje nasjonalbiblioteket har hatt en feil?
